# Extended extra fragments support
ifeq ($(KERNEL_CONFIG_USE_EXTRA_FRAGMENTS),1)
KERNEL_CONFIG_DEVICE_FRAGMENTS += $(patsubst %, $(KERNEL_SOURCES)/droidian/%, $(KERNEL_CONFIG_EXTRA_FRAGMENTS))
endif
ifeq ($(KERNEL_CONFIG_USE_DEVEL_FRAGMENTS),1)
KERNEL_CONFIG_DEVICE_FRAGMENTS += $(patsubst %, $(KERNEL_SOURCES)/droidian/%, $(KERNEL_CONFIG_DEVEL_FRAGMENTS))
endif
ifeq ($(KERNEL_CONFIG_USE_DEBUG_FRAGMENTS),1)
KERNEL_CONFIG_DEVICE_FRAGMENTS += $(patsubst %, $(KERNEL_SOURCES)/droidian/%, $(KERNEL_CONFIG_DEBUG_FRAGMENTS))
endif
